/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;

import com.toedter.calendar.JDateChooser;
import java.sql.Connection;
import java.sql.Statement;
import mainclass.dbConnection;
import java.awt.HeadlessException;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JFormattedTextField;
import javax.swing.text.DateFormatter;
/**
 *
 * @author ASUS
 */
public class adminPinjamBuku extends javax.swing.JFrame {
DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form adminbuku
     */
    public void tampilkan_data(){
            model.addColumn("id_peminjaman");
            model.addColumn("NIM");
            model.addColumn("NIP");
            model.addColumn("id_Admin");
            model.addColumn("id_Buku");
            model.addColumn("Tgl_Pinjam");
            model.addColumn("Tgl_Kembali");

            
            
            
            try{
                String sql = "SELECT * FROM peminjaman";
                java.sql.Connection kon = (Connection)dbConnection.dbConnection();
                java.sql.Statement stat = kon.createStatement();
                java.sql.ResultSet res = stat.executeQuery(sql);
                
                while (res.next()){
                    model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4), res.getString(5), res.getString(6), res.getString(7)});
                }   
                
                tabelpinjam.setModel(model);
     
            }catch (SQLException e){
                System.out.println("error : " + e.getMessage());
            }
        }    
    public adminPinjamBuku() {
        initComponents();
        tampilkan_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        hapus = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        idpinjam = new javax.swing.JTextField();
        nim = new javax.swing.JTextField();
        nip = new javax.swing.JTextField();
        idbuku = new javax.swing.JTextField();
        idadmin = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelpinjam = new javax.swing.JTable();
        tanggalpinjam = new com.toedter.calendar.JDateChooser();
        tanggalkembali = new com.toedter.calendar.JDateChooser();
        kembali = new javax.swing.JButton();
        editbuku = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(":");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(772, 440));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Book Borrow Form");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(270, 20, 326, 57);

        hapus.setText("Delete");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel1.add(hapus);
        hapus.setBounds(550, 350, 63, 23);

        tambah.setText("Add");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        jPanel1.add(tambah);
        tambah.setBounds(390, 350, 51, 23);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Borrower  id     ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 120, 96, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NIM");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 160, 120, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NIP");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 200, 130, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Book id          ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 240, 110, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Borrowed date ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 320, 110, 17);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Admin_id ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 280, 110, 17);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Back date  ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 360, 80, 17);
        jPanel1.add(idpinjam);
        idpinjam.setBounds(130, 110, 180, 30);
        jPanel1.add(nim);
        nim.setBounds(130, 150, 180, 30);
        jPanel1.add(nip);
        nip.setBounds(130, 190, 180, 30);
        jPanel1.add(idbuku);
        idbuku.setBounds(130, 230, 180, 30);
        jPanel1.add(idadmin);
        idadmin.setBounds(130, 270, 180, 30);

        tabelpinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelpinjam);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(370, 90, 430, 250);

        tanggalpinjam.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(tanggalpinjam);
        tanggalpinjam.setBounds(130, 310, 180, 30);

        tanggalkembali.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(tanggalkembali);
        tanggalkembali.setBounds(130, 350, 180, 30);

        kembali.setText("Back");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(kembali);
        kembali.setBounds(40, 420, 55, 23);

        editbuku.setText("Edit buku");
        editbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbukuActionPerformed(evt);
            }
        });
        jPanel1.add(editbuku);
        editbuku.setBounds(460, 350, 77, 23);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/1222dd.jpg"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 850, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
       adminlogin a = new adminlogin();
        a.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_kembaliActionPerformed

    private void editbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbukuActionPerformed
        // TODO add your handling code here:
        adminEditBuku a = new adminEditBuku();
        a.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_editbukuActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        int id_pinjam = Integer.parseInt(idpinjam.getText());
        int NIM = Integer.parseInt(nim.getText());
        int NIP = Integer.parseInt(nip.getText());
        int id_buku = Integer.parseInt(idbuku.getText());
        int id_admin = Integer.parseInt(idadmin.getText());
        
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tglpinjam = String.valueOf(fm.format(tanggalpinjam.getDate()));
//        java.sql.Date sql = new java.sql.Date(tanggalpinjam.getDate());
        SimpleDateFormat kmb = new SimpleDateFormat(tampilan);
        String tglkembali = String.valueOf(kmb.format(tanggalkembali.getDate()));
        
        try{
            java.sql.Connection con = (Connection) dbConnection.dbConnection();
            Statement statement= con.createStatement();
            String insert = "INSERT INTO `peminjaman` VALUES ('"+id_pinjam+"','"+NIM+"','"+NIP+"', '"+id_buku+"', '" + id_admin +"', '"+tglpinjam+"', '"+tglkembali+"')"; 
            statement.executeUpdate(insert);
            
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
        } catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
    }
        idpinjam.setText("");
        nim.setText("");
        nip.setText("");
        idbuku.setText("");
        idadmin.setText("");
    }//GEN-LAST:event_tambahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        int row = tabelpinjam.getSelectedRow();
        if(row>=0){
            int ok = JOptionPane.showConfirmDialog(null, "Yakin Mau Hapus?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            model.removeRow(row);
            if(row == 0){
                model.removeRow(row);
            }
        }        
    }//GEN-LAST:event_hapusActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(adminPinjamBuku.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminPinjamBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminPinjamBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminPinjamBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminPinjamBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminPinjamBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton editbuku;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField idadmin;
    private javax.swing.JTextField idbuku;
    private javax.swing.JTextField idpinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField nim;
    private javax.swing.JTextField nip;
    private javax.swing.JTable tabelpinjam;
    private javax.swing.JButton tambah;
    private com.toedter.calendar.JDateChooser tanggalkembali;
    private com.toedter.calendar.JDateChooser tanggalpinjam;
    // End of variables declaration//GEN-END:variables
}
